---
title: "03 Riesgos Hidrometeorológicos y Sanitarios"
output: html_document
---

# 3 Riesgos Hidrometeorológicos y Sanitarios
```{r, warning=FALSE, echo=TRUE, message=FALSE}
source('../../utils.R')
# options(httr_oob_default=TRUE) 
# token <- gs_auth(new_user = TRUE, cache = FALSE)
# saveRDS(token, file = "../googlesheets_token.rds")
# KEY <- readRDS("../googlesheets_token.rds")
# Direct url download
download_path <- 'https://drive.google.com/uc?export=download&id={id}'
```

# Nombres municipios
```{r, warning=FALSE, echo=TRUE, message=FALSE}
#Nombre archivo: 
# Datos/Socioeconómico/CONEVAL_indicadores de pobreza municipal, 2015.csv
# Nivel: cve_muni

id <- '1PPG_5yDMMrJ4E5Q_Gp3mbawb50gu7y1L'
url <-glue::glue(download_path)
dic_muni <-  read_csv(url,
                        locale = readr::locale(encoding = "latin3")) %>% 
  filter(clave_entidad == 8) %>% 
  mutate(nom_mun = iconv(str_to_lower(municipio),from="UTF-8",to="ASCII//TRANSLIT")) %>% 
  select(cve_mun=clave_municipio, nom_mun)
```

## 3.1 Calidad de Agua
```{r, warning=FALSE, echo=TRUE, message=FALSE}
# Calidad del agua de uso y consumo humano. (COFEPRIS)
#Nombre archivo: 
# Chihuahua/Datos/Riesgos/COFEPRIS_Agua_Calidad_2016
# Fuente: Cofepris
# Nivel: cve_muni
id <- '1_iPKHpS3-emXvhx2CcLQOTBdfGUNolJq'
url <-glue::glue(download_path)
consumo_humano <-  read_csv(url,
                        locale = readr::locale(encoding = "latin3"),skip = 1) %>% 
  filter(Estado == 'CHIHUAHUA', Mes == "Diciembre") %>% 
  mutate(nom_mun = iconv(str_to_lower(Municipio),from="UTF-8",to="ASCII//TRANSLIT")) %>% 
  select(nom_mun, 
         pct_de_Determinaciones_dentro_de_norma = `% de Determinaciones dentro de norma`) %>% 
  left_join(dic_muni, by = "nom_mun") %>% 
  filter(!is.na(cve_mun)) %>% 
  mutate(cve_mun = str_extract(cve_mun, regex("[0-9]{3}$")),
         cve_ent = '08') %>% 
  select(cve_ent, cve_mun, pct_de_Determinaciones_dentro_de_norma)
consumo_humano
```


```{r, warning=FALSE, echo=TRUE, message=FALSE}
#Nombre archivo: 
# Chihuahua/Datos/Riesgos/coespris_comunidades arsenico fluor.xlsx
# Fuente: Coespris
# Nivel: localidad
id <- '1eHVCsrOJLC33cu8fkIHyWWt7WYfC_mdh'
url <-glue::glue(download_path)
arsenico <- read_excel_url(url, sheet = 'arsenico') %>%
  mutate(cve_loc = str_pad(`No. Localidad`,4,'left','0'),
         cve_mun = str_pad(`No. Municipio`,3,'left','0'),
         cve_ent = '08',
         arsenico=TRUE) %>%
  select(cve_ent, cve_loc, cve_mun, pob_afect_arsenico = Poblacion)

# fluor
# Coespris
fluor <- read_excel_url(url, sheet = 'fluor') %>%
  mutate(cve_loc = str_pad(`No. Localidad`,4,'left','0'),
         cve_mun = str_pad(`No. Municipio`,3,'left','0'),
         cve_ent = '08',
         fluor=TRUE) %>%
  select(cve_ent, cve_loc, cve_mun, pob_afect_fluor = Poblacion)
```
## 3.2 Amenazas Hidrometeorológicas
```{r, warning=FALSE, echo=TRUE, message=FALSE}

#Nombre archivo: 
# Chihuahua/Datos/Riesgos/CONAGUA_riesgo_por_sequia_2015
# Fuente: Conagua
# Nivel: cve_mun
id <- "1yVynmOxqER3eqKTJPJXe3M47G5VzaKiT"
url <-glue::glue(download_path)
riesgo_sequia <- read_csv(url) %>%
  mutate(cve_mun = str_extract(cve_mpio,'[0-9]{3}$'), 
         cve_mun = str_pad(cve_mun,3,'left','0'), 
         cve_ent = str_pad(as.character(id_edo),2,'left','0')) %>% 
  dplyr::rename(riesgo_sequia=Riesgo) %>% 
  select(cve_ent, cve_mun, riesgo_sequia) %>% 
  filter(cve_ent=='08')

#Nombre archivo: 
# Chihuahua/Datos/Riesgos/cenapred_app_municipios.csv
# Fuente: CENAPRED
# Nivel: cve_mun
id <- "1y6Rn45a1igU5ma8PMiXuKjGMf4gyqtby"
url <-glue::glue(download_path)
riesgo_inundacion <- read_csv(url) %>% 
  mutate(cve_mun = str_extract(cve_muni,'[0-9]{3}$'), 
         cve_mun = str_pad(cve_mun,3,'left','0'), 
         cve_ent = str_pad(as.character(cve_ent),2,'left','0')) %>% 
  select(cve_ent, cve_mun, riesgo_indundacion=GP_Inundac) %>% 
  filter(cve_ent=='08') 
riesgo_inundacion
```



# Unión y Bases finales - Dimensión Riesgos
### 3.1 Final -  Calidad de Agua
```{r, warning=FALSE, echo=TRUE, message=FALSE}
calidad_agua <- dplyr::full_join(arsenico, fluor, 
                                 by = c("cve_ent", "cve_loc", "cve_mun")) %>% 
  left_join(consumo_humano, by = c("cve_ent","cve_mun"))
calidad_agua %>% write_rds("../../data/chihuahua/3_1_calidad_agua_cve_loc.rds")
calidad_agua
```

### 3.2 Final - Amenazas Hidrometeorológicas
```{r, warning=FALSE, echo=TRUE, message=FALSE}
amenaza_hidro <- full_join(riesgo_sequia, riesgo_inundacion, by = c("cve_ent", "cve_mun"))
amenaza_hidro %>% write_rds("../../data/chihuahua/3_2_amenaza_hidro_cve_mun.rds")
amenaza_hidro
```
