---
title: "linea_de_base"
output: html_document
---


```{r, results='hide', warning=FALSE, echo=FALSE, message=FALSE}
# rm(list = ls())
source('../../utils.R') 
```

# Upload
```{r, results='hide', warning=FALSE, echo=FALSE, message=FALSE}
path<-"../../data/chihuahua/"
file_list <- list.files(path)
for (i in 1:length(file_list)){
   oname = file_list[[i]]
   outname = str_c('db_',str_remove(oname, ".rds"))
   assign(outname, read_rds(str_c(path, oname)))
}
dim_colnames <- list()
```


Obtenemos población para poder calcular tasas por 100 mil habitantes
- Ahorita lo ejecutamos con la población total
```{r, warning=FALSE, echo=TRUE, message=FALSE}
#Nombre archivo: 
# Datos/Socioeconómico/
# Nivel: cve_muni
id <- '12vWfJVI7LAh0aW7h8Yxggu4mNfg8Ywjk'
url <-glue::glue(download_path)
poblacion <- read_csv(url) %>%
  mutate(cve_mun = str_extract(cve_muni,'[0-9]{3}$'), 
         cve_ent = str_extract(cve_muni,'^[0-9]{2}')) %>% 
  select(cve_ent, cve_mun, poblacion_total=Total_Total) # contains("Total")) 
names(poblacion) <- names(poblacion) %>%
  clean_names()

poblacion
```



# 01 Infraestructura

```{r, results='hide', warning=FALSE, echo=FALSE, message=FALSE}
# Transformación
db_1_2_infra_salud_mun <- db_1_2_infra_salud_clues %>%
  select(cve_ent, cve_mun, agua_potable:baños_discapacitados) %>% 
  group_by(cve_ent, cve_mun) %>% 
  # Promedio por número de escuelas
  summarise_each(funs(sum(., na.rm = T)/n())) # %>% 
  # filter(!is.na(cve_ent))
summary(db_1_2_infra_salud_mun)

#  01 Infraestructura
infraestructura <- left_join(db_1_1_infra_escolar_cct, db_1_2_infra_salud_mun,
                             by = c("cve_ent", "cve_mun")) %>% 
  left_join(db_1_3_infra_muni_cve_muni, by = c("cve_ent", "cve_mun"))

infraestructura %>%
  write_rds("../../data/01_infraestructura.rds")

plot_missing(infraestructura)  + theme_grey(base_size = 5)
dim_colnames["col_infraestructura"] <- list(colnames(infraestructura))
```

# 02 Educación

```{r, results='hide', warning=FALSE, echo=FALSE, message=FALSE}
educacion <- full_join(db_2_1_desempeño_cct, db_2_2_agentes_recursos_cct,
                       by=c("cct","cve_ent","cve_mun","cve_loc", "cve_turno")) %>% 
  left_join(db_2_3_rezago_municipal_cve_muni, by=c("cve_ent", "cve_mun")) %>% 
  select(-poblacion)

educacion %>%
  write_rds("../../data/02_educacion.rds")
plot_missing(educacion)  + theme_grey(base_size = 5)
dim_colnames["col_educacion"] <- list(colnames(educacion))

```
# 03 Riesgos
```{r}
# localidad
db_3_1_calidad_agua_cve_mun <- db_3_1_calidad_agua_cve_loc %>% 
  group_by(cve_ent, cve_mun) %>% 
  dplyr::summarise(pob_afect_arsenico=sum(pob_afect_arsenico, na.rm = T),
            pob_afect_fluor=sum(pob_afect_fluor, na.rm = T))
riesgos <- db_3_1_calidad_agua_cve_mun %>% 
  full_join(db_3_2_amenaza_hidro_cve_mun,
            by=c("cve_ent","cve_mun"))

riesgos %>%
  write_rds("../../data/03_riesgos.rds")
plot_missing(riesgos)  + theme_grey(base_size = 5)
dim_colnames["col_riesgos"] <- list(colnames(riesgos))
```

# 04 Salud

```{r}
# 04 Salud
salud <- full_join(db_4_1_morbilidad_cve_muni, db_4_2_mortalidad_cve_muni,
                   by=c("cve_ent","cve_mun")) %>% 
  left_join(poblacion, by=c("cve_ent", "cve_mun")) %>% 
  mutate(tasa_morbilidad_relacionada = morbilidad_relacionada/poblacion_total*100000,
         tasa_mortalidad_relacionada = mortalidad_relacionada/poblacion_total*100000) %>% 
    select(cve_ent, cve_mun, tasa_morbilidad_relacionada, tasa_mortalidad_relacionada) 
  
salud %>%
  write_rds("../../data/04_salud.rds")
plot_missing(salud)  + theme_grey(base_size = 5)
dim_colnames["col_salud"]  <- list(colnames(salud))
```

```{r}
# 05 intervención
# Nivel localidad
db_5_3_riesgo_cve_mun <- db_5_3_riesgo_cve_loc %>% 
  group_by(cve_ent, cve_mun) %>% 
  dplyr::summarise(poi_beneficiarios=sum(poi_beneficiarios, na.rm = T),
                   poi_num=sum(poi_operacion, na.rm = T)) %>% 
  mutate(poi_operacion=if_else(poi_num>=1,1,0))


intervencion <- db_5_1_alimentacion_cct %>%
  full_join(select(db_5_2_talleres_clues_cct, cct, talleres),
            by=c("cct")) %>%
  # obtener cve_ent y cve_mun / definimos la base de infraestructura como goldstandard
  full_join(select(infraestructura, cct, cve_ent, cve_mun), by ="cct") %>% 
  left_join(db_5_3_riesgo_cve_mun, by=c("cve_ent", "cve_mun")) %>% 
  distinct() %>% 
  drop_na(cve_ent, cve_mun)
intervencion %>%
  write_rds("../../data/05_intervencion.rds")

plot_missing(intervencion)  + theme_grey(base_size = 5)
dim_colnames["col_intervencion"] <- list(colnames(intervencion))

```


# Base Final
```{r, results='hide', warning=FALSE, echo=FALSE, message=FALSE}
#rm(list = ls())

infraestructura <- read_rds("../../data/01_infraestructura.rds")
educacion <- read_rds("../../data/02_educacion.rds")
riesgos <- read_rds("../../data/03_riesgos.rds")
salud <- read_rds("../../data/04_salud.rds")
intervencion <- read_rds("../../data/05_intervencion.rds")

# linea_de_base
linea_de_base <- full_join(infraestructura, educacion, by=c("cve_ent","cve_mun","cct", "cve_loc")) %>% 
  left_join(riesgos, by=c("cve_ent","cve_mun")) %>% 
  left_join(salud, by=c("cve_ent","cve_mun")) %>% 
  full_join(intervencion, by=c("cve_ent","cve_mun", "cct")) # %>% 
  # select( c("cve_ent", "cve_mun", "cve_loc", "cct"), 
  #        setdiff(colnames(infraestructura), c("cve_ent", "cve_mun", "cve_loc", "cct")),
  #        setdiff(colnames(educacion), c("cve_ent", "cve_mun", "cve_loc", "cct")),
  #        setdiff(colnames(riesgos), c("cve_ent", "cve_mun")),
  #        setdiff(colnames(salud), c("cve_ent", "cve_mun")),
  #        setdiff(colnames(intervencion), c("cve_ent", "cve_mun", "cve_loc", "cct"))) 

linea_de_base$cve_ent <- "08"
linea_de_base %>% 
  write_rds("../../data/linea_de_base_t.rds")

dim_colnames %>% 
  write_rds("../../data/dim_colnames.rds")

```
